use AMITH;
SELECT * FROM AMITH.STUDENT;

CREATE TABLE STUDENT(STUDENT_ID INT PRIMARY KEY,STUDENT_NAME VARCHAR(20) NOT NULL,DEPARTMENT VARCHAR(20) default 'CSE'); 
INSERT INTO STUDENT VALUES(145,"RAM","CSE",0.5);
INSERT INTO STUDENT(STUDENT_NAME,DEPARTMENT,GPA) VALUES("SAI","CSE",0.9);

ALTER TABLE STUDENT MODIFY STUDENT_NAME VARCHAR(30);

DELETE FROM STUDENT WHERE STUDENT_ID=148;

UPDATE STUDENT SET STUDENT_NAME="RAM DEEPAK" WHERE STUDENT_ID=145;

DROP TABLE STUDENT;

SELECT * FROM STUDENT;




desc STUDENT;
SELECT * FROM STUDENT;
ALTER TABLE STUDENT ADD GPA int;
-- ALTER TABLE STUDENT DROP COLUMN GPA;
drop table STUDENT;

INSERT INTO STUDENT VALUES(147,"MANI","CSE",90);
SELECT * FROM STUDENT;



INSERT INTO STUDENT VALUES(140,"ADD","CSE",30);

SHOW TRIGGERS 
FROM AMITH
LIKE '%SAMPLE%';

drop table STUDENT;
SHOW TABLES;


-- Creating A Trigger 

CREATE trigger SAMPLE_TRIGGER BEFORE INSERT ON STUDENT FOR EACH ROW SET NEW.GPA=NEW.GPA/10;
SELECT * FROM SAMPLE_TRIGGER;

create trigger new_trigger after insert on STUDENT for each row insert into trigger_test values("value Inserted");

